export const quizSteps = [
  {
    id: 1,
    type: "info",
    title: "Welcome to your\nShort Journey",
    image: "welcome.png",
    text: "This is the moment you stop drifting through city chaos and start steering your life.\nSmart women like you deserve quiet control – not endless hustle. Ready for your first gentle step?",
    buttonText: "Let’s begin together",
  },
  {
    id: 2,
    type: "question",
    title: "Life in city feels like a whirlwind",
    text: "Career pressure, family needs, rising rent… where are you in all this overwhelm?\nWe see you. This journey returns your power, softly.",
    answers: [
      { id: "a", answer: "I feel lost sometimes" },
      { id: "b", answer: "Too much pressure" },
      { id: "c", answer: "Ready to take control" },
    ],
  },
  {
    id: 3,
    type: "info",
    title: "Beautiful honesty –\nthat’s step one",
    image: "Beautiful-honesty.png",
    buttonText: "Next step",
  },
  {
    id: 4,
    type: "info",
    title: "Bodo Schäfer says:",
    image: "Bodo.png",
    text: "“Most people don’t live – they are lived by their circumstances.”\n\nCity life tests this daily.\nBut you?\nYou’re about to flip the switch.\n\nOne decision away from a different life.",
    buttonText: "Yes, I am",
  },
  {
    id: 5,
    type: "info",
    title: "Your life feels like TV – someone else holds the remote?",
    image: "Your-life-feels.png",
    text: "City bosses, economy, “bad timing” change channels. But Bodo Schäfer teaches: You can take the remote back.\nNo blame. Just ask: “What can I control right now?” Quiet power returns.",
    buttonText: "I want the remote",
  },
  {
    id: 6,
    type: "question",
    title: "Who Really Controls You?",
    text: "Recent frustration (boss yelling? rent spike?): Who “made” you feel that way? City life tests this daily. Your answer reveals who holds the remote.",
    answers: [
      { id: "a", answer: "My boss/economy –\nthey controls me" },
      { id: "b", answer: "Circumstances pushed me there" },
      { id: "c", answer: "I let myself feel it – I control" },
    ],
  },
  {
    id: 7,
    type: "info",
    variants: {
      a: {
        title: "They seem powerful, but they don’t own you",
        image: "They-seem-powerful.png",
        text: "They seem to hold remote, but you choose your reaction. Blaming gives your power away. Take remote back: “What can I control here?” You’re stronger than city drama.",
        buttonText: "Taking it back",
      },
      b: {
        title: "External Pressure ≠ You",
        image: "They-seem-powerful.png",
        text: "Circumstances knock, but you choose if door opens. External pressure doesn’t equal your feelings. Remote always yours – even in NYC rent hikes or bad meetings.",
        buttonText: "My remote",
      },
      c: {
        title: "Perfect Awareness!",
        image: "They-seem-powerful.png",
        text: "YES! “I am responsible” = ultimate power. You control channels, not vice versa. Beautiful city-woman wisdom. This mindset changes everything softly.",
        buttonText: "I feel powerful",
      },
    },
  },
  {
    id: 8,
    type: "info",
    title: "Remote Is Yours Now",
    image: "Remote-Is-Yours-Now.png",
    text: "Beautiful choice! “I am responsible for my feelings.” Boss emails? Remote yours. Rent hikes? Yours too. One decision flips city life softly.",
    buttonText: "Feels powerful",
  },
  {
    id: 9,
    type: "question",
    title: "Power Check-In",
    text: "Taking remote back – how does it feel? City women like you reclaim power daily through this simple mindset shift.",
    answers: [
      { id: "a", answer: "A little empowering" },
      { id: "b", answer: "Yes! Strong shift" },
      { id: "c", answer: "Still processing" },
    ],
  },
  {
    id: 10,
    type: "info",
    title: "Less Blame, More You",
    image: "Less-Blame.png",
    text: "Perfect! Imagine less blame tomorrow on subway – more “I got this” moments. City chaos tests, you hold remote. New baseline established.",
    buttonText: "Love this feeling",
  },
  {
    id: 11,
    type: "info",
    title: "Graceful Ownership",
    image: "Graceful-Ownership.png",
    text: "You’re owning power so gracefully. Ready to point your remote at your heart’s clear goal? Best part coming up.",
    buttonText: "Ready for goals",
  },
  {
    id: 12,
    type: "info",
    title: "Natural Energy Flow",
    image: "Natural-Energy-Flow.png",
    text: "“I control my remote” energy flows perfectly into clear goals. Quiet strength building naturally. You’re doing beautifully.",
    buttonText: "Let’s flow",
  },
  {
    id: 13,
    type: "info",
    title: "Clarity Awaits",
    image: "Clarity-Awaits.png",
    text: "Lovely work! Carrying “I hold the remote” feeling into crystal clear goals next. Power + direction = unstoppable magic.",
    buttonText: "Next Block – Goals",
  },
  {
    id: 14,
    type: "info",
    title: "Foggy Dreams vs Clear Compass",
    image: "Foggy-Dreams.png",
    text: "City women dream “better life someday” but circle endlessly. Clear goal = warm compass light cutting morning fog. One specific 12-month target + tiny steps = movement toward your North Star.",
    buttonText: "Show me the compass",
  },
  {
    id: 15,
    type: "question",
    title: "Which Goal Lights Your Way?",
    text: "Which goal pulls your heart through city chaos? Vague dreams fade in traffic. Crystal ones guide you home.",
    answers: [
      { id: "a", answer: "Someday better life" },
      { id: "b", answer: "Less daily stress" },
      { id: "c", answer: "+$1,000/mo in 12 months\nfrom new skill" },
    ],
  },
  {
    id: 16,
    type: "info",
    variants: {
      a: {
        title: "Dream Needs Direction",
        image: "Dream-Needs.png",
        text: "“Someday better” = fog without compass. Heart needs: What? By when? How much? City life demands specifics or you drift. Try: “In 12 months, $X more doing Y.”",
        buttonText: "Make it specific",
      },
      b: {
        title: "Feelings Need Feet",
        image: "Dream-Needs.png",
        text: "“Less stress” = valid heart cry, but needs action + timeline. What creates calm? By when? Measure it. “Stress down 30% by June via Z” = compass working.",
        buttonText: "Add action/timeline",
      },
      c: {
        title: "Your North Star Found",
        image: "Dream-Needs.png",
        text: "YES! Specific + timed + actionable = magnetic pull. Brain now reverse-engineers daily steps. City chaos can’t stop compass clarity. This is how you arrive.",
        buttonText: "Feels magnetic",
      },
    },
  },
  {
    id: 17,
    type: "info",
    title: "One Goal Changes Everything",
    image: "One-Goal.png",
    text: "Compass locked! Tomorrow you wake with direction, not “what now?” fog. One clear goal rewires city overwhelm into purposeful steps.",
    buttonText: "Love this clarity",
  },
  {
    id: 18,
    type: "question",
    title: "Heart Check-In",
    text: "Does your heart whisper a specific goal now? Even forming = progress for busy urban women.",
    answers: [
      { id: "a", answer: "Starting to form" },
      { id: "b", answer: "Crystal clear!" },
      { id: "c", answer: "Still emerging" },
    ],
  },
  {
    id: 19,
    type: "info",
    title: "Compass Cuts Chaos",
    image: "Compass-Cuts-Chaos.png",
    text: "Smart awareness! Clear goals slice city chaos like compass through fog. Yours forming beautifully – subway thoughts now have direction.",
    buttonText: "Feels true",
  },
  {
    id: 20,
    type: "info",
    title: "Purposeful Mornings",
    image: "Purposeful-Mornings.png",
    text: "Your heart knows direction. One goal pulls through busy weeks, late calls, endless meetings.\nCompass > calendar.",
    buttonText: "Excited",
  },
  {
    id: 21,
    type: "info",
    title: "No More “What Now?”",
    image: "No-More.png",
    text: "Imagine mornings with purpose vs overwhelm fog. Coffee + compass > coffee + confusion. You’re building this.",
    buttonText: "Yes please",
  },
  {
    id: 22,
    type: "info",
    title: "Clarity + Power = Magic",
    image: "Clarity-Power-Magic.png",
    text: "Gorgeous flow! Remote control (Block 1) + compass (Block 2) = unstoppable city-woman magic. Tiny brave steps next.",
    buttonText: "Next Block – Brave Steps",
  },
  {
    id: 23,
    type: "info",
    title: "Butterflies Build Strength",
    image: "Butterflies-Build-Strength.png",
    text: "Confidence doesn’t magic-up amid city chaos. It grows from tiny brave steps – even with butterflies from 7am meetings. You don’t need “ready.” One small step despite fear = brain learning “I can.”",
    buttonText: "Show me tiny steps",
  },
  {
    id: 24,
    type: "question",
    title: "Scared of That Side Project?",
    text: "Nervous about side hustle (amid city grind)? Best gentle move? Fear tests urban women daily. Your choice builds courage muscle.",
    answers: [
      { id: "a", answer: "Wait until no fear" },
      { id: "b", answer: "Tiny step today, butterflies OK" },
      { id: "c", answer: "Ask friends first" },
    ],
  },
  {
    id: 25,
    type: "info",
    variants: {
      a: {
        title: "Fear Shrinks AFTER Moving",
        image: "Fear-Shrinks.png",
        text: "Fear rarely vanishes before action – it shrinks after your first step. Waiting = stuck in city paralysis. Tiny step despite butterflies = confidence compound interest.",
        buttonText: "Step despite fear",
      },
      b: {
        title: "Butterflies + Action = Growth",
        image: "Fear-Shrinks.png",
        text: "YES! “Step despite butterflies” = courage muscle. Each tiny “yes despite fear” rewires brain: “I handle scary things.” City women win this way.",
        buttonText: "Feels brave",
      },
      c: {
        title: "Your Steps > Their Words",
        image: "Fear-Shrinks.png",
        text: "Friends’ encouragement warms heart, but confidence grows from YOUR action. Their “you got this” + your tiny step = unstoppable combo. Don’t wait for applause.",
        buttonText: "My steps matter",
      },
    },
  },
  {
    id: 26,
    type: "info",
    title: "One Step = Tomorrow’s Confidence",
    image: "One-Step-Tomorrows.png",
    text: "Tiny step today = confidence tomorrow. You’re training heart in courage. Fear shrinks, you expand. Every micro-brave = city-proof strength brick.",
    buttonText: "Building strength",
  },
  {
    id: 27,
    type: "question",
    title: "Butterflies Check-In",
    text: "Butterflies normal for brave steps? Successful city women feel them too – then step anyway.",
    answers: [
      { id: "a", answer: "Totally normal" },
      { id: "b", answer: "Usually feel them" },
      { id: "c", answer: "Getting fewer" },
    ],
  },
  {
    id: 28,
    type: "info",
    title: "Rewiring Confidence",
    image: "Rewiring-Confidence.png",
    text: "Smart! Every “step despite butterflies” rewires confidence permanently. Subway doubts become “I did that” memories.",
    buttonText: "Love this truth",
  },
  {
    id: 29,
    type: "info",
    title: "Courage Muscle Growing",
    image: "Courage-Muscle-Growing.png",
    text: "You’re building courage muscle. Tiny steps = big inner strength over months. City pressure forges diamonds.",
    buttonText: "Feels powerful",
  },
  {
    id: 30,
    type: "info",
    title: "City Stress, Brave Heart",
    image: "City-Stress.png",
    text: "Imagine handling city stress with growing quiet confidence. Late trains? Boss curveballs? You step forward anyway.",
    buttonText: "Ready for more",
  },
  {
    id: 31,
    type: "info",
    title: "Brave + Compass = Unstoppable",
    image: "Brave-Compass.png",
    text: "Perfect flow! Remote (1) + Compass (2) + Brave Steps (3) = city-woman superpower. Self-worth foundation next.",
    buttonText: "Next Block – Self-Worth",
  },
  {
    id: 32,
    type: "info",
    title: "Worth Beyond Results",
    image: "Worth-Beyond-Results.png",
    text: "You’re worthy ALWAYS – beyond work flops, rent stress, unmet goals. Presentation bombed? Doesn’t redefine you. You’re woman learning/growing. This truth lets you breathe through city pressure.",
    buttonText: "Show me worth",
  },
  {
    id: 33,
    type: "question",
    title: "Work Mistake – Your Thought?",
    text: "Mistake happened (we’ve all survived those meetings). Kindest thought? Self-worth test for urban warriors.",
    answers: [
      { id: "a", answer: "I’m a total failure" },
      { id: "b", answer: "Work all night to prove" },
      { id: "c", answer: "Mistake ≠ my worth – I’ll learn" },
    ],
  },
  {
    id: 34,
    type: "info",
    variants: {
      a: {
        title: "One Mistake ≠ You",
        image: "One-Mistake.png",
        text: "“Failure” attacks your whole self – unfair to beautiful you. Slip = data, not identity. Separate: “I slipped, still worthy + learning.” City pros grow this way.",
        buttonText: "Bigger than mistakes",
      },
      b: {
        title: "Work Smart, Not Desperate",
        image: "One-Mistake.png",
        text: "Hard work great, but panic “prove myself” burns out city women. Worth first → sustainable effort. “I’m valuable + improving” fuels marathons.",
        buttonText: "Love over panic",
      },
      c: {
        title: "Perfect Self-Love",
        image: "One-Mistake.png",
        text: "YES! “Mistake ≠ worth” = freedom. Learn fast without wing-breaking. City chaos bounces off this foundation. You’re unbreakable now.",
        buttonText: "Feels freeing",
      },
    },
  },
  {
    id: 35,
    type: "info",
    title: "Your Quiet Foundation",
    image: "Your-Quiet-Foundation.png",
    text: "Self-worth = unbreakable foundation. Remote + Compass + Brave + Worth = complete city-woman toolkit. Everything grows from here.",
    buttonText: "Solid foundation",
  },
  {
    id: 36,
    type: "question",
    title: "Worth Check-In",
    text: "Easier breathing knowing worth > results? Urban women owning this change everything.",
    answers: [
      { id: "a", answer: "Breathing easier" },
      { id: "b", answer: "Starting to feel" },
      { id: "c", answer: "Truth sinking in" },
    ],
  },
  {
    id: 37,
    type: "info",
    title: "Grace Under City Pressure",
    image: "Grace-Under-City.png",
    text: "Smart! Unshakable worth handles pressure gracefully. Late deadlines? Wrong turns? You = worthy + capable.",
    buttonText: "Grateful for this",
  },
  {
    id: 38,
    type: "info",
    title: "Superpower Complete",
    image: "Superpower-Complete.png",
    text: "Remote control + Compass + Brave steps + Worth foundation = YOUR superpower. Ready for personal challenge?",
    buttonText: "Yes! Challenge me",
  },
  {
    id: 39,
    type: "textarea",
    title: "Your 2-Min Magic Challenge",
    step: "Step 1 of 3",
    text: "Type here your stuck spot?",
    secondaryText: "(career/money/habits)",
    placeholder: "Enter your answer here",
    buttonText: "Next",
  },
  {
    id: 40,
    type: "textarea",
    title: "Your 2-Min Magic Challenge",
    step: "Step 2 of 3",
    text: "Type here your 12-month goal",
    secondaryText: "(specivic!)",
    placeholder: "Enter your answer here",
    buttonText: "Next",
  },
  {
    id: 41,
    type: "textarea",
    title: "Your 2-Min Magic Challenge",
    step: "Step 3 of 3",
    text: "Type here your tomorrow tiny step",
    placeholder: "Enter your answer here",
    afterText: "Remote + Compass active – write your power!",
    buttonText: "Next",
  },
  {
    id: 42,
    type: "info",
    title: "Day 1 Mastered!",
    image: "Day-1-Mastered.png",
    text: "BEAUTIFUL work! Goal + step typed = quiet magic launched. You’ve got remote, compass, courage, worth. Ready for Day 2?",
    buttonText: "Create free account to continue",
  },
];
