import "./sprints.css";

import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

import { TimerProvider } from "./actions/useTimerContext";

export const metadata = {
  title: "ChatMND",
  description: "Generated by create next app",
};

export default function SprintsLayout({ children }) {
  return (
    <>
      <TimerProvider initialSeconds={30}>
        <Header />
        <>{children}</>
        <Footer />
      </TimerProvider>
    </>
  );
}
