import "./sprints.css";

import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

import { TimerProvider } from "./actions/useTimerContext";
import { PlanSelectionProvider } from "./actions/planSelectionContext";

export const metadata = {
  title: "ChatMND",
  description: "Generated by create next app",
};

export default function SprintsLayout({ children }) {
  return (
    <>
      <PlanSelectionProvider>
        <TimerProvider initialSeconds={720}>
          <Header />
          <>{children}</>
          <Footer />
        </TimerProvider>
      </PlanSelectionProvider>
    </>
  );
}
