import "./sprints.css";

import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

export const metadata = {
  title: "ChatMND",
  description: "Generated by create next app",
};

export default function SprintsLayout({ children }) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  );
}
