import "./styles.kidstvb2b.css";

export const metadata = {
  title: "KidsTV",
  description: "Generated by create next app",
};

export default function FilmsLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
