import "./styles.films.css";

export const metadata = {
  title: "KIVI protective films",
  description: "Generated by create next app",
};

export default function FilmsLayout({ children }) {
  return <div className="films-wrapper">{children}</div>;
}
