import { Montserrat } from "next/font/google";
import "./styles.films.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "latin-ext", "cyrillic"],
  weight: ["400", "500", "600", "700"],  
});

export const metadata = {
  title: "KIVI protective films",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <div className={montserrat.variable}>
        {children}
      </div>
    </>
  );
}
