import { Montserrat } from "next/font/google";
import "./styles.films.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "latin-ext", "cyrillic"],
  weight: ["400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "KIVI protective films",
  description: "Generated by create next app",
};

export default function FilmsLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>{children}</body>
      {/* <body>{children}</body> */}
    </html>
  );
}
