import "./intensives.films.css";

export const metadata = {
  title: "Intensives quiz",
  description: "Generated by create next app",
};

export default function IntensivesLayout({ children }) {
  return <div className="intensives-wrapper">{children}</div>;
}
