import "./intensives.css";

import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";

export const metadata = {
  title: "Intensives quiz",
  description: "Generated by create next app",
};

export default function IntensivesLayout({ children }) {
  return (
    <>
      <Header />
      <>{children}</>
      <Footer />
    </>
  );
}
