export const FeedbackData = [
  {
    id: 1,
    text: "I didn’t realize how much my phone was stealing my day. After a week, I’m more dialed in at work and finishing tasks again.",
    img: "/images/sprints/choose-plan/feedback-01.png",
    nickname: "@inn.marine",
    forBranch: "focus",
  },
  {
    id: 2,
    text: "I’d start five things and finish none. These tools keep me on one track longer — less mental noise.",
    img: "/images/sprints/choose-plan/feedback-02.png",
    nickname: "@andrew_m88",
    forBranch: "focus",
  },
  {
    id: 3,
    text: "The biggest win is starting. I open it, do the first step, and I’m moving — no more staring at my to-do list.",
    img: "/images/sprints/choose-plan/feedback-03.png",
    nickname: "@helgascrow",
    forBranch: "focus",
  },
  {
    id: 4,
    text: "My focus used to crash by lunch. Now I have a quick rhythm to reset when I drift — I get real work done.",
    img: "/images/sprints/choose-plan/feedback-04.png",
    nickname: "@tomtkwr_",
    forBranch: "focus",
  },
  {
    id: 5,
    text: "I expected hacks. It’s more like structure: short focus blocks + tools that keep me from getting scattered.",
    img: "/images/sprints/choose-plan/feedback-05.png",
    nickname: "@ellakn",
    forBranch: "focus",
  },
  {
    id: 11,
    text: "I usually drop habits by week two. This time it’s small enough to keep, even when my week gets busy.",
    img: "/images/sprints/choose-plan/feedback-01.png",
    nickname: "@inn.marine",
    forBranch: "habits",
  },
  {
    id: 22,
    text: "When my week gets messy, I don’t ‘restart’. I just pick it back up the next day — that’s new for me.",
    img: "/images/sprints/choose-plan/feedback-02.png",
    nickname: "@andrew_m88",
    forBranch: "habits",
  },
  {
    id: 33,
    text: "I always went all-in and burned out. Starting smaller felt too easy, but it’s the first thing that’s stuck.",
    img: "/images/sprints/choose-plan/feedback-03.png",
    nickname: "@helgascrow",
    forBranch: "habits",
  },
  {
    id: 44,
    text: "I thought I lacked motivation. Turns out I needed a routine that fits my life — this helped me build it.",
    img: "/images/sprints/choose-plan/feedback-04.png",
    nickname: "@tomtkwr_",
    forBranch: "habits",
  },
  {
    id: 55,
    text: "Progress without obsessing is huge. Small daily wins add up, and I’m not fighting myself all day.",
    img: "/images/sprints/choose-plan/feedback-05.png",
    nickname: "@ellakn",
    forBranch: "habits",
  },
  {
    id: 111,
    text: "My mind used to run nonstop at night. After a couple weeks, I can switch off faster — less overthinking, better sleep.",
    img: "/images/sprints/choose-plan/feedback-01.png",
    nickname: "@inn.marine",
    forBranch: "stress",
  },
  {
    id: 222,
    text: "I didn’t expect tiny practices to help. When stress spikes, I have a quick reset instead of spiraling.",
    img: "/images/sprints/choose-plan/feedback-02.png",
    nickname: "@andrew_m88",
    forBranch: "stress",
  },
  {
    id: 333,
    text: "It helped me spot patterns — what triggers me and what calms me. I feel steadier day to day.",
    img: "/images/sprints/choose-plan/feedback-03.png",
    nickname: "@helgascrow",
    forBranch: "stress",
  },
  {
    id: 444,
    text: "I’m still busy, but I’m less on edge. It feels like I get a breather during the day.",
    img: "/images/sprints/choose-plan/feedback-04.png",
    nickname: "@tomtkwr_",
    forBranch: "stress",
  },
  {
    id: 555,
    text: "I used to numb out with scrolling. Now I have better ways to decompress, and my mood swings aren’t as sharp.",
    img: "/images/sprints/choose-plan/feedback-05.png",
    nickname: "@ellakn",
    forBranch: "stress",
  },
  {
    id: 1111,
    text: "I kept stopping after a few days. The plan makes it doable — short clear steps, and I’m finally consistent.",
    img: "/images/sprints/choose-plan/feedback-01.png",
    nickname: "@inn.marine",
    forBranch: "shape",
  },
  {
    id: 2222,
    text: "Late-night snacking was my weak spot. I haven’t ‘fixed’ everything, but I make better choices more often.",
    img: "/images/sprints/choose-plan/feedback-02.png",
    nickname: "@andrew_m88",
    forBranch: "shape",
  },
  {
    id: 3333,
    text: "I chased fast results and burned out. This is steadier, and my energy feels better already.",
    img: "/images/sprints/choose-plan/feedback-03.png",
    nickname: "@helgascrow",
    forBranch: "shape",
  },
  {
    id: 4444,
    text: "Tracking made me obsessive, then I’d quit. Here it’s simple, so I can stick with it without stress.",
    img: "/images/sprints/choose-plan/feedback-04.png",
    nickname: "@tomtkwr_",
    forBranch: "shape",
  },
  {
    id: 5555,
    text: "No extreme plans. Just consistent movement and smarter eating tools — and I feel stronger week by week.",
    img: "/images/sprints/choose-plan/feedback-05.png",
    nickname: "@ellakn",
    forBranch: "shape",
  },
  {
    id: 11111,
    text: "I picked ‘all of the above’ because everything felt messy. One bundle gave me a system, and my days feel less chaotic.",
    img: "/images/sprints/choose-plan/feedback-01.png",
    nickname: "@inn.marine",
    forBranch: "universal",
  },
  {
    id: 22222,
    text: "Instead of fixing everything at once, it helped me tackle the biggest blocker first — the rest got easier.",
    img: "/images/sprints/choose-plan/feedback-02.png",
    nickname: "@andrew_m88",
    forBranch: "universal",
  },
  {
    id: 33333,
    text: "I used to bounce between apps and routines. Now it’s one plan + tools that fit, and I’m actually following through.",
    img: "/images/sprints/choose-plan/feedback-03.png",
    nickname: "@helgascrow",
    forBranch: "universal",
  },
  {
    id: 44444,
    text: "I needed balance, not pressure. This feels supportive and realistic, even on busy weeks.",
    img: "/images/sprints/choose-plan/feedback-04.png",
    nickname: "@tomtkwr_",
    forBranch: "universal",
  },
  {
    id: 55555,
    text: "I expected overwhelm. But it’s a small set of apps that work well together — progress feels simpler.",
    img: "/images/sprints/choose-plan/feedback-05.png",
    nickname: "@ellakn",
    forBranch: "universal",
  },
  {
    id: 666666,
    text: "Did the math — my old subscriptions cost more. Here it’s one bundle of 3 premium apps I actually use.",
    img: "/images/sprints/choose-plan/feedback-06.png",
    nickname: "@taylorphoto",
    forBranch: "all",
  },
  {
    id: 777777,
    text: "The quiz picked apps that match my goal — so I’m not downloading random stuff and quitting after a week.",
    img: "/images/sprints/choose-plan/feedback-07.png",
    nickname: "@thl.mark",
    forBranch: "all",
  },
  {
    id: 888888,
    text: "One payment, one place to manage it — no more surprise renewals or “wait, what am I paying for?” moments.",
    img: "/images/sprints/choose-plan/feedback-08.png",
    nickname: "@lialia.fj",
    forBranch: "all",
  },
  {
    id: 999999,
    text: "I like that it’s a bundle AND a plan — the apps make sense together, instead of fighting for my attention.",
    img: "/images/sprints/choose-plan/feedback-10.png",
    nickname: "@m0nclaire",
    forBranch: "all",
  },
  {
    id: 101010,
    text: "I thought bundles were a gimmick — but this one saved me money and cut the subscription chaos.",
    img: "/images/sprints/choose-plan/feedback-09.png",
    nickname: "@sjensen3",
    forBranch: "all",
  },
];
